pipeline {
    agent any

    environment {
        IMAGE_NAME = "ankitkolhe10/django_docker10:latest"
        
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', 
                    url: 'https://github.com/SRCEM-AIM-Class-A/django_docker10'
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${IMAGE_NAME} ."
                }
            }
        }

        
        stage('Push Docker Image') {
             steps {
                withDockerRegistry([credentialsId: 'docker-ankitkolhe10', url: 'https://index.docker.io/v1/']) {
                    sh "docker push ${IMAGE_NAME}"
                }
            }
        }
    }
}
