pipeline {
    agent any

    environment {
        IMAGE_NAME = "ankitkolhe10/django_docker10"
        
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', 
                    url: 'https://github.com/SRCEM-AIM-Class-A/django_docker10'
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    def dockerImage = docker.build("${env.IMAGE_NAME}", "-f Dockerfile .")
                }
            }
        }

        
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-ankitkolhe10') {
                        def dockerImage = docker.image("${env.IMAGE_NAME}")
                        dockerImage.push()
                    }
                }
            }
        }

    }
}
